### ISSUE TITLE
Application closes without notice if Settings clicked without having any devices connected. 

### ISSUE THREAD

**Issue by fsgl1tch** [meshtastic/Meshtastic-gui-installer#102]
Either the clicking the Settings without devices connected shows a warning or the settings menu could be disabled till a device is connected (greyed out). I would say that disabled button seems the most reasonable. Design decision time!

**Comment by mkinney** [comment]
It is a catch-22. I don't really know if there is a device connected until the Settings button is pressed.

On the prior version 1.0.71, it would just simply close m-flasher if there were no devices connected. In the latest version, it shows a dialog that the user needs to plugin a device.

**Comment by mkinney** [comment]
If you're running from a cloned repo, you may need to:

```
git checkout master
git pull
pip install .
meshtastic-flasher
```

**Comment by fsgl1tch** [comment]
Yes, it seems that in newer versions the Settings for no device is handled more gracefully!
