### ISSUE TITLE
user reports that "The GUI doesn’t work in high Sierra"

### ISSUE THREAD

**Issue by mkinney** [meshtastic/Meshtastic-gui-installer#123]
GrimReaper user on Discord reported that the GUI doesn’t work in high Sierra.

**Comment by mkinney** [comment]
Not sure we want to support OS's this old.

**Comment by mkinney** [comment]
<img width="851" alt="Screen Shot 2022-03-07 at 3 55 52 PM" src="https://user-images.githubusercontent.com/2219838/157138345-839e1485-56fa-40b1-83fc-186cf6b34ea6.png">

**Comment by mkinney** [comment]
Per: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners 

<img width="770" alt="Screen Shot 2022-03-30 at 11 59 30 AM" src="https://user-images.githubusercontent.com/2219838/160910726-e2cb7ae1-a0f3-404a-864f-7be51117185c.png">

May consider using  macOS Catalina 10.15 or `macos-10.15` for the mac release runner.

**Comment by garthvh** [comment]
Expected
