### ISSUE TITLE
[Bug]: Wifi password hardcoded as 'sekrit'

### ISSUE THREAD

**Issue by SigmaScott** [meshtastic/Meshtastic-gui-installer#124]
### Category

WiFi

### Hardware

T-Beam

### Firmware Version

v1.2.56.596a73c 
meshtastic flasher version 1.0.88

### Description

When using the meshtastic flasher to config a device the password is set to 'sekrit' even after setting the password to correct password.

**Comment by bobatgit** [comment]
Hi Folks!

I'm experiencing the same issue with two of my TTGO lora boards. Any time I set a wifi password it gets reset back to "sekrit" after saving it on the device. So, I'm unable to connect via WiFi at all.

Any advice on how I can fix this password issue? Thanks!

**Device type:** tlora-v1
**Flasher version:** v1.0.102 
**Firmware version:** 1.2.59.d8c1c0.

Cheers,
Bob
