### ISSUE TITLE
user reports "detected" text is garbled

### ISSUE THREAD

**Issue by mkinney** [meshtastic/Meshtastic-gui-installer#130]
user reports "detected" text is garbled

The white color txt in Left side-middle about the installed FW version, is garbled, out of focus, not one line txt words is on top of other words.

https://meshtastic.discourse.group/t/meshtastic-gui-installer-flasher-big-thank-you/5232

win10

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/meshtastic-gui-installer-flasher-big-thank-you/5232/3

**Comment by mkinney** [comment]
<img width="689" alt="Screen Shot 2022-03-05 at 4 54 49 PM" src="https://user-images.githubusercontent.com/2219838/156904692-2345602a-ce93-42c6-89e8-6376ab22e27f.png">

**Comment by mkinney** [comment]
<img width="690" alt="Screen Shot 2022-03-05 at 5 00 13 PM" src="https://user-images.githubusercontent.com/2219838/156904794-aa3ab42e-e475-43bc-9165-3f250a9e1e57.png">

**Comment by mkinney** [comment]
https://github.com/meshtastic/Meshtastic-gui-installer/releases/tag/1.0.90
