### ISSUE TITLE
Meshtastic Flasher WinApp 1.0.0 detected as a trojan

### ISSUE THREAD

**Issue by OwensDataCenter** [meshtastic/Meshtastic-gui-installer#145]
This issue was created for this post on Reddit: https://www.reddit.com/r/Lora/comments/tctwlc/meshtasticflasherzip_download_detected_as_a_virus/?utm_source=share&utm_medium=web2x&context=3

Virus detected: Trojan:Win32/Wacatac.B!ml

**Comment by thebentern** [comment]
See #141
