### ISSUE TITLE
add pylint to ci

### ISSUE THREAD

**Issue by mkinney** [meshtastic/Meshtastic-gui-installer#15]

**Comment by RishiKumarRay** [comment]
I tried adding pylint workflow , this is happening
![Screenshot from 2022-02-01 10-23-33](https://user-images.githubusercontent.com/87641376/151914723-c3d8b4e3-a636-467f-ae4b-940987b6f082.png)

**Comment by mkinney** [comment]
Then pylint is working!

**Comment by RishiKumarRay** [comment]
@should i raise PR adding this workflow for pylint?

**Comment by RishiKumarRay** [comment]
If you allow?

**Comment by mkinney** [comment]
Sure. I cannot see the code that generates that. PRs are most welcome!

**Comment by RishiKumarRay** [comment]
@mkinney I have added workflow for pylint please check

**Comment by mkinney** [comment]
Looks great. Thanks again.

**Comment by RishiKumarRay** [comment]
@mkinney You need to fix that wrong import position so the pylint will not fail but thanks for merging

**Comment by mkinney** [comment]
I fixed it with a new PR

:-)

**Comment by RishiKumarRay** [comment]
great :)

**Comment by mkinney** [comment]
If you're not already on Discord, there's an active Meshtastic group https://discord.gg/UQJ5QuM7vq

**Comment by RishiKumarRay** [comment]
Thanks , I have joined
