### ISSUE TITLE
Flash a TLora with default ttgo sketch, then try to use m-flasher to install Meshtastic flasher

### ISSUE THREAD

**Issue by mkinney** [meshtastic/Meshtastic-gui-installer#159]
Flash a TLora with default ttgo sketch, then try to use m-flasher to install Meshtastic flasher to see if there are any issues with that scenario.

**Comment by garthvh** [comment]
This same issue seems to happen if a tbeam device has SoftRF too

**Comment by garthvh** [comment]
Some issues with Meshtastic 1.0 devices

**Comment by garthvh** [comment]
I have some inconsistencies with the same devices with the install script as well, as sometimes it takes several attempts to succeed on MacOS, seems to work more consistently on linux.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/errors-while-running-the-flasher-fatal-error-when-writing-to-target/5517/4
