### ISSUE TITLE
fails to detect actual device

### ISSUE THREAD

**Issue by jutshanahan** [meshtastic/Meshtastic-gui-installer#160]
I have a Tbeam however the software thinks a Tlora-v2-1 is detected. 
![image](https://user-images.githubusercontent.com/1766455/158303546-3ee95593-afba-4b6e-8030-2a44b31c81be.png)

**Comment by mkinney** [comment]
Expand the Device drop down list. It detected that it could be one of several devices.

**Comment by mkinney** [comment]
Just created a PR that adds this screen after the detection:

<img width="534" alt="Screen Shot 2022-03-15 at 8 14 25 PM" src="https://user-images.githubusercontent.com/2219838/158509856-a3a0c720-f8cd-4617-948a-5ff4347d5f90.png">
