### ISSUE TITLE
Bad value write when use a float value in adc_multiplier_override field

### ISSUE THREAD

**Issue by amerinoj** [meshtastic/Meshtastic-gui-installer#181]
Hello I was playing with POWER settings and realize that the "adc multiplier override" don't work with float values.

For example if you try to put a 1.2 as value in POWER(adc_multiplier_override) this send  " Set adc_multiplier_override to 0 " .
This field only work with integer values and should work with float values.

**Comment by caveman99** [comment]
The protobufs define it as "float adc_multiplier_override" - so the value can be a float. Have you tried setting it with the meshtastic CLI?

**Comment by amerinoj** [comment]
In meshtastic CLI working fine, but when you put a decimal in GUI send 0

**Comment by mkinney** [comment]
Thanks for reporting the issue. Will be fixed in next release.

**Comment by mkinney** [comment]
Fixed in latest release: https://github.com/meshtastic/Meshtastic-gui-installer/releases/tag/1.0.102
