### ISSUE TITLE
WiFi AP Mode should be a radio selection

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-gui-installer#189]
WiFi AP Mode should be a radio selection. Eg:

WiFi Client (x) WiFi Access Point ( )

... or something along those lines.

<img width="978" alt="image" src="https://user-images.githubusercontent.com/12804989/160954588-969f7147-b9b0-4c9b-b543-36805d9c2741.png">

**Comment by garthvh** [comment]
Totally refactored for 1.3 if implemented will use the new enum
