### ISSUE TITLE
bug: detect TLora-v21.6 as TBeam

### ISSUE THREAD

**Issue by diamondbarcode** [meshtastic/Meshtastic-gui-installer#207]
I am running Meshtastic Flasher V1.0.105 on Windows 11 , python 3.10

It detect correct version of meshtastic i installed on device but just wrong devices populated. It happen for while i forgot to report it.

I have to manual select devices.

`
start of detect
Detected T-Beam
Detected T-Lora
Detected T-Lora
Detected T-Beam
Detected T-Beam
Detected T-Lora
Detected Nano G1
Detected T-Lora
Detected T-Beam
User confirmed the device has Meshtastic so we will check using the Meshtastic python method
Warning: Could not find any ports using the Meshtastic python autodetection method.
from find_ports ports:['COM11']
Getting version and hwModel from Meshtastic python library
filenames:['1.2.63.9879494\\firmware-heltec-v1-1.2.63.9879494.bin', '1.2.63.9879494\\firmware-heltec-v2.0-1.2.63.9879494.bin', '1.2.63.9879494\\firmware-heltec-v2.1-1.2.63.9879494.bin', '1.2.63.9879494\\firmware-meshtastic-diy-v1-1.2.63.9879494.bin', '1.2.63.9879494\\firmware-nano-g1-1.2.63.9879494.bin', '1.2.63.9879494\\firmware-rak11200-1.2.63.9879494.bin', '1.2.63.9879494\\firmware-tbeam-1.2.63.9879494.bin', '1.2.63.9879494\\firmware-tbeam0.7-1.2.63.9879494.bin', '1.2.63.9879494\\firmware-tlora-v1-1.2.63.9879494.bin', '1.2.63.9879494\\firmware-tlora-v2-1-1.6-1.2.63.9879494.bin', '1.2.63.9879494\\firmware-tlora-v2-1.2.63.9879494.bin', '1.2.63.9879494\\firmware-tlora_v1_3-1.2.63.9879494.bin']
self.detected_list:[]
end of detect
`

**Comment by garthvh** [comment]
Consolidating detection issue to https://github.com/meshtastic/Meshtastic-gui-installer/issues/233
