### ISSUE TITLE
Multiple devices connected

### ISSUE THREAD

**Issue by JeffCrum1** [meshtastic/Meshtastic-gui-installer#209]
I have two devices connected to this laptop.

It gives me the error:
Warning: Multiple serial ports were detected so one serial port must be specified with the '--port'.
  Ports detected:['COM3', 'COM4']

Is the software not using the  port selected in the UI?
![image](https://user-images.githubusercontent.com/94788212/166163092-64413036-9ffe-4f26-883a-6c04643e799c.png)

**Comment by mkinney** [comment]
No, it currently does not use the port in that drop down when you select "Device Settings" because of the NRF devices. I'm assuming that's the option you selected.
