### ISSUE TITLE
Flasher problem

### ISSUE THREAD

**Issue by Ciumaros** [meshtastic/Meshtastic-gui-installer#213]
Hello! I am triing to flash Meshtastic from windows via usb and uhen I klick detect device i get in cmd promt  among other text. this mesage. I'm no python user and i'm not shure how can i solve the problem... Can you help me?

File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x83 in position 36800: character maps to <undefined>

**Comment by garthvh** [comment]
Not able to replicate
