### ISSUE TITLE
problem detecting t-beam 

### ISSUE THREAD

**Issue by danielsonpfeiffer** [meshtastic/Meshtastic-gui-installer#230]
Getting the error "Had a problem talking with the device." Have tried uplugging and replugging, but seems to keep being an issue...

**Comment by JebBaker** [comment]
How are you connecting?  With the Flasher/UI?

**Comment by danielsonpfeiffer** [comment]
I was trying to use the Flasher and couldn’t get it working on my PC, but got it working on the Mac!
Is version 1.2.65 a good option?

Dan

On Aug 16, 2022, at 12:46 PM, JebBaker ***@***.***> wrote:

﻿

How are you connecting? With the Flasher/UI?

**Comment by garthvh** [comment]
Consolidating detection issue to https://github.com/meshtastic/Meshtastic-gui-installer/issues/233
