### ISSUE TITLE
Flasher Meshtastic: In device settings you can only set region

### ISSUE THREAD

**Issue by KONRAD1322222222** [meshtastic/Meshtastic-gui-installer#235]
So like in topic. In device settings you can only set region. I run tbeam on version 1.3.40.e87ec2, with meshtastic flasher v1.3.22 and I got something like that.

![IMG_20220915_112926](https://user-images.githubusercontent.com/113592501/190369661-95135cc7-4c0f-4416-9470-727132becb9f.jpg)

However it should looks like that
![Zrzut ekranu z 2022-09-15 11-36-28](https://user-images.githubusercontent.com/113592501/190370478-1f47bed9-3713-4fad-b554-11080cc84242.png)

Thank you for your help in advance and I know from telegram and one more guy has the same issue.

**Comment by garthvh** [comment]
The settings have been re-factored in 1.3 and the flasher offers a much more limited set of options. This is a volunteer project and there have been no contributions to restore this functionality.

**Comment by garthvh** [comment]
> Ok, but is there any way to dowload maybe previous version of flasher and just program on older version?

https://meshtastic.org/docs/1.2-End-of-life/
