### ISSUE TITLE
Missing Menus in advanced Settings

### ISSUE THREAD

**Issue by damianburrin** [meshtastic/Meshtastic-gui-installer#242]
Updated to latest version of the flasher - thanks for the population fix.

Am I doing something daft.  Shouldn't I be able to set the modules and configure the device through this - I could with the stand alone version.

I only get the option to set my region now

![image](https://user-images.githubusercontent.com/18092613/194761846-438e13f6-2d22-4d98-8574-9e1126fe1a7b.png)

**Comment by garthvh** [comment]
For 1.3 the flasher is back to being for flashing firmware, other than region there are no settings available.  Config is available in the CLI, on iOS or via the hosted webui client.meshtastic.org for android devices.
