### ISSUE TITLE
Can not run Meshtastic-flasher on Debian 9

### ISSUE THREAD

**Issue by rezabinesh** [meshtastic/Meshtastic-gui-installer#244]
Hi there,

I'm using Debian 9 and installed Python 3.7 and PIP 3.7
I've followed all the steps to install Mestastic-Flasher without any error. In the last step when I try to run the flasher, I get below error:

(venv) root@debian:~/Python-3.7.3# meshtastic-flasher
Traceback (most recent call last):
  File "/root/Python-3.7.3/venv/bin/meshtastic-flasher", line 5, in <module>
    from meshtastic_flasher.main import main
  File "/root/Python-3.7.3/venv/lib/python3.7/site-packages/meshtastic_flasher/main.py", line 7, in <module>
    from PySide6.QtGui import QIcon
ImportError: libQt6Core.so.6: cannot open shared object file: No such file or directory

Anyone has a clue or a similar experience?

Thanks.

**Comment by caveman99** [comment]
Debian 9 LTS support expired on Jun 30th 2022. you could try installing libQT6 packages but you're on your own there. The flasher and the CLI should support python 3.7.x although newer versions may work better.
