### ISSUE TITLE
The version scroll menu does not work

### ISSUE THREAD

**Issue by tompatulpan** [meshtastic/Meshtastic-gui-installer#245]
With more than one version detected, it is not possible to chose them from version menu.
Tested on Meshtastic flasher v1.3.27

![Screenshot from 2022-10-13 12-26-13_](https://user-images.githubusercontent.com/13780294/195613202-8439c42b-4034-4f2a-b790-e0c1b7587b26.png)

**Comment by garthvh** [comment]
The flasher is currently set to offer the most recent stable version

**Comment by tompatulpan** [comment]
Ok, understood. It would be nice though if scroll down to alpha/beta versions could be done in future and maybe stable on top?
