### ISSUE TITLE
[Unsightliness] On https://flasher.meshtastic.org/ the Favicon is missing.

### ISSUE THREAD

**Issue by Dtrieb** [meshtastic/Meshtastic-gui-installer#257]
On https://flasher.meshtastic.org/ the Favicon is missing.

![chrome_2022-11-14_20-07-41](https://user-images.githubusercontent.com/3650284/201744995-cb72ee5f-9779-4119-a7b8-99fa10fef22d.png)

**Comment by garthvh** [comment]
The web flasher is a different repo
