### ISSUE TITLE
No such file or Directory

### ISSUE THREAD

**Issue by QuadPrime** [meshtastic/Meshtastic-gui-installer#261]
Hello, while using the Meshtastic Flasher 2.0.2 I came across a minor bug: It said everything was going fine, erased the Memory and then the esptool threw an error "no such file or directory 2.0.13.7e27729\firmware-tbeam-2.0.13.7e27729.bin".

and that makes sense, because that exact file didnt exist. It was created as firmware-tbeam-2.0.13.7e27729-d.bin .

deleted the "-d" from the filename and it appeas to have worked!

best regards and respect for your project. please continue it.

**Comment by caveman99** [comment]
closing, as this is a packaging issue that's already noticed. next release will work normally again.
