### ISSUE TITLE
Qt problem @ Ubuntu 22.04

### ISSUE THREAD

**Issue by dh2pp** [meshtastic/Meshtastic-gui-installer#271]
Hello everyone :wave:

I ran into a problem when launching ```meshtastic-flasher``` in a bash / and / or zsh on my ubuntu 22.04 machine. This is the output. I assume this has to do with some Qt version incompatibility...

```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: offscreen, wayland, minimal, eglfs, xcb, wayland-egl, vkkhrdisplay, minimalegl, linuxfb, vnc.

[1]    48424 IOT instruction (core dumped)  meshtastic-flasher
```

**Comment by garthvh** [comment]
Please use the web flasher for esp32 or the drag and drop for nrf. The python flasher is not being worked on.
