### ISSUE TITLE
Forcing 921600 baud rate causes flash failure on tbeam

### ISSUE THREAD

**Issue by TheRealTachyon** [meshtastic/Meshtastic-gui-installer#55]
As with the device-install.sh script, this GUI installer fails because it uses the forced baud rate option with 921600 as the baud rate.
Simply removing the baud rate option to esptool allows the tool to auto-negotiate the baud rate correctly and the flashing succeeds.

Note that this is fixed in the included device-install.sh script that comes with firmware-1.2.53.19c1f9f so that installer could be used for reference in fixing Meshtastic-gui-installer

**Comment by mkinney** [comment]
The fix has been pushed to pypi but github errored out on the mac single executable build. So, if you want/need it right away from pypi, go for it.

**Comment by mkinney** [comment]
Released
