### ISSUE TITLE
update bootloaders for NRF52 (not to be confused with Meshtastic firmware)

### ISSUE THREAD

**Issue by mkinney** [meshtastic/Meshtastic-gui-installer#9]
https://github.com/meshtastic/Meshtastic-device/blob/50ec03229f7d28812451fbd27e6c82872a7ae066/bin/uf2conv.py

https://github.com/meshtastic/Meshtastic-device/blob/94246a1fbc37e7cb62f4e1d0a3a8edf71d8f9479/bin/upload-to-rak4631.sh

**Comment by mkinney** [comment]
Updated the RAK bootloader

This might pertain to T-Echo, right @garthvh ?

**Comment by mkinney** [comment]
see https://github.com/Xinyuan-LilyGO/LilyGO-T-Echo/tree/main/bootloader

Opened https://github.com/Xinyuan-LilyGO/LilyGO-T-Echo/issues/9

**Comment by garthvh** [comment]
The Adafruit nrfutil should just work with a techo I think.

**Comment by mkinney** [comment]
Ok. A zip file was provided by RAK. I don’t see equivalent from LilyGo.

Might need to look inside that zip file. There was a manifest and a couple of small files.

**Comment by mkinney** [comment]
```
manifest.json
sd_bl.bin
sd_bl.dat
```

```
% cat manifest.json
{
    "manifest": {
        "dfu_version": 0.5,
        "softdevice_bootloader": {
            "bin_file": "sd_bl.bin",
            "bl_size": 39000,
            "dat_file": "sd_bl.dat",
            "init_packet_data": {
                "application_version": 4294967295,
                "device_revision": 52840,
                "device_type": 82,
                "firmware_crc16": 1054,
                "softdevice_req": [
                    65534
                ]
            },
            "sd_size": 151016
        }
    }
}%
```

**Comment by mkinney** [comment]
The https://github.com/lyusupov/SoftRF/blob/master/software/firmware/binaries/nRF52840/Adafruit_nRF52_Bootloader/LilyGO_TEcho_bootloader-0.6.1.zip has the `update-lilygo_techo_bootoader-0.6.1_nosd.uf2` file that successfully updated my T-Echo. Reports same data. 

[AFTER_INFO_UF2.TXT](https://github.com/meshtastic/Meshtastic-gui-installer/files/8037884/AFTER_INFO_UF2.TXT)
[B4_INFO_UF2.TXT](https://github.com/meshtastic/Meshtastic-gui-installer/files/8037885/B4_INFO_UF2.TXT)

Need to add that to m-flasher.
