### ISSUE TITLE
Having trouble flashing T-Beam

### ISSUE THREAD

**Issue by jaredmiller23** [meshtastic/Meshtastic-gui-installer#94]
I've tried this several times, and it keeps hitting a dead end with this message:
Step 2/4 esp32 full
ESPTOOL Using command:--port COM9 write_flash 0x1000 1.2.55.9db7c62/system-info.bin
usage: esptool write_flash [-h] [--erase-all] [--flash_freq {keep,40m,26m,20m,80m}]
                           [--flash_mode {keep,qio,qout,dio,dout}] [--flash_size FLASH_SIZE]
                           [--spi-connection SPI_CONNECTION] [--no-progress] [--verify] [--encrypt]
                           [--encrypt-files <address> <filename> [<address> <filename> ...]]
                           [--ignore-flash-encryption-efuse-setting] [--compress | --no-compress]
                           <address> <filename> [<address> <filename> ...]
esptool write_flash: error: argument <address> <filename>: [Errno 2] No such file or directory: '1.2.55.9db7c62/system-info.bin'

**Comment by mkinney** [comment]
I think you need to install a device driver

**Comment by mkinney** [comment]
Oh. I just re-read your issue. My first comment was wrong.

I think the firmware file was not downloaded/unzipped correctly.

Open up the directory, and remove the directory "1.2.55.9db7c62".

**Comment by mkinney** [comment]
Added #110 to maybe make this easier

**Comment by mkinney** [comment]
Added option in "Advanced Options" (hot key "A" at the main program) to "Clear Firmware Files". If you click that button, close the form, click "Get Versions", then the firmware file/versions will be re-downloaded from github. Then you should be able to proceed.

**Comment by mkinney** [comment]
Going to close this issue due to no response from user. If this is still and issue, feel free to re-open issue or open a new issue.

**Comment by jaredmiller23** [comment]
MKinney,

My sincere apologies for not responding, life got in the way.  I appreciate your help.  I’m glad you added that option to clear, it made it much easier for a newb like myself.  Thank you very much - I appreciate your efforts!

Have a great day!

JM
