### ISSUE TITLE
Button property 'PointingHandCursor' not set for all clickable buttons

### ISSUE THREAD

**Issue by fsgl1tch** [meshtastic/Meshtastic-gui-installer#98]
Buttons _GET VERSIONS_ and _DETECT DEVICES_ do not have a pointing hand once hovered over the button, but _Help_ and _Settings_ do.

**Comment by fsgl1tch** [comment]
Not sure if this intended, but I created a pull request that adds pointing hand style cursor style to other buttons (see https://github.com/meshtastic/Meshtastic-gui-installer/pull/101)

**Comment by mkinney** [comment]
Looks great. Thanks.
